spring:
  application:
    name: "restaurant-api"

  datasource:
    url: ${app.db.url:jdbc:h2:mem:restaurantDB}
    driver-class-name: ${app.db.driver:org.h2.Driver}
    username: ${app.db.username:sa}
    password: ${app.db.password:}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


server:
  port: ${app.port:8080}

logging:
  level:
    root: ${app.log.level:info}
minio:
  access-key: ${minio.access-key:minio}
  secret-key: ${minio.secret-key:secret123}
  qr-bucket: ${minio.qr-bucket:qr-code}
